"""Build data/news.js: recent news coverage of campus sexual-assault cases.

Pulls Google News RSS search results for a set of queries, keeps items from the last 60 days,
de-duplicates them and writes headline, outlet, date and link. Headlines are shown as published by
each outlet and always link to the original article.
Run: python scripts/fetch_news.py  (needs network access to news.google.com)
"""
import email.utils
import json
import re
import sys
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

QUERIES = [
    '"sexual assault" university lawsuit',
    '"sexual assault" college student charged',
    'campus rape lawsuit',
    'fraternity "sexual assault" lawsuit',
    '"Title IX" "sexual assault" investigation university',
    'college athlete "sexual assault" charged',
    'university doctor "sexual abuse" settlement',
    '"Clery Act" fine university',
    'student "sexual assault" sentenced university',
]
MAX_AGE_DAYS = 60
MAX_ITEMS = 150
# At least one of these must appear in the headline, so unrelated stories are dropped.
CAMPUS_WORDS = re.compile(r"\b(universit|college|campus|student|fraternit|sororit|Title IX|Clery|dorm|athlete|coach|professor)", re.I)
# This tracker covers US colleges: drop K-12 stories and coverage of campuses abroad.
EXCLUDE_WORDS = re.compile(r"\b(high school|middle school|elementary|K-12|school district|India|Indian|Punjab|Delhi|Mumbai|Kolkata|Bengal|Kerala|Pakistan|Bangladesh|Nigeria|Kenya|Uganda|Ghana|Philippines|Australia|Australian|Canada|Canadian|UK|British|England|Scotland|Ireland|China|Chinese|Japan|Korea|Vietnam|LPU)\b", re.I)
FOREIGN_OUTLETS = re.compile(r"(India|NDTV|Livemint|Rediff|ABP|TheWire\.in|NewsX|Gulf News|Hindustan|Deccan|Tribune India|Dawn|Punch|VnExpress|Korea|Straits|SCMP|ABC \(Australia\)|CBC|BBC|Guardian Nigeria)", re.I)
ABUSE_WORDS = re.compile(r"\b(rape|raped|sexual|sex abuse|sex assault|assault|abuse|misconduct|Title IX|Clery)", re.I)


def fetch(q):
    url = "https://news.google.com/rss/search?" + urllib.parse.urlencode({"q": q + " when:60d", "hl": "en-US", "gl": "US", "ceid": "US:en"})
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (campus-assault-tracker news build)"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return ET.fromstring(r.read())


def norm(title):
    return re.sub(r"[^a-z0-9 ]", "", title.lower())[:90]


def main():
    now = time.time()
    items, seen = [], set()
    for q in QUERIES:
        try:
            root = fetch(q)
        except Exception as e:  # noqa: BLE001 - one failed query should not stop the build
            print(f"query failed: {q}: {e}", file=sys.stderr)
            continue
        for it in root.iter("item"):
            title = (it.findtext("title") or "").strip()
            link = (it.findtext("link") or "").strip()
            source = (it.findtext("source") or "").strip()
            pub = it.findtext("pubDate")
            if not (title and link and pub):
                continue
            ts = email.utils.parsedate_to_datetime(pub).timestamp()
            if now - ts > MAX_AGE_DAYS * 86400:
                continue
            # Google News appends " - Outlet" to titles; show the outlet separately.
            if source and title.endswith(" - " + source):
                title = title[: -len(" - " + source)]
            if not (CAMPUS_WORDS.search(title) and ABUSE_WORDS.search(title)):
                continue
            if EXCLUDE_WORDS.search(title) or FOREIGN_OUTLETS.search(source):
                continue
            key = norm(title)
            if key in seen:
                continue
            seen.add(key)
            items.append({"t": title, "s": source, "u": link, "d": int(ts)})
        time.sleep(1)

    items.sort(key=lambda x: -x["d"])
    items = items[:MAX_ITEMS]
    print(f"{len(items)} news items", file=sys.stderr)
    if not items:
        sys.exit("no news items fetched; keeping the previous data/news.js")
    data = {"updated": int(now), "items": items}
    with open("data/news.js", "w") as f:
        f.write("// Generated by scripts/fetch_news.py - do not edit by hand.\n")
        f.write("window.NEWS = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    main()
